services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
        command: >
            sh -c "
                php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration &&
                php bin/console doctrine:fixtures:load --no-interaction &&
                php -S 0.0.0.0:8337 -t public
            "
        networks:
            - sio_network
        depends_on:
           sio_test_db:
               condition: service_healthy
                   
    sio_test_db:
        image: postgres:17.5-alpine
        restart: always
        env_file:
            - .env
        ports:
            - "5444:5432"
        expose:
            - 5432
        networks:
            - sio_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - sio_db_data:/var/lib/postgresql/data:rw
networks:
    sio_network:
volumes:
    sio_db_data: